keys:
  - &zimbatm age1tk655t40a4zx7ry0mzj57vmw4xpr7sa0c8qnckmclj5gzjls4yzsk7weg0

creation_rules:
  - path_regex: ^secrets/hosts/demo-nuc-002\.yaml$
    key_groups:
      - age:
          - age1tt507kehguvukgkdpdepvsqlsdz0mdr9tf0q9udctyqyg56n2sqqz6crv6
          - *zimbatm
